"""baseline

Revision ID: 4ca3ca774ca4
Revises:
Create Date: 2026-04-28 15:12:17.405944

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ca3ca774ca4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "songs",
        sa.Column("uuid", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("artwork_thumb", sa.Text(), nullable=True),
        sa.Column("artwork_full", sa.Text(), nullable=True),
        sa.Column("parent_song_id", sa.Text(), nullable=True),
        sa.Column("root_song_id", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Text(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_song_id"], ["songs.uuid"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["root_song_id"], ["songs.uuid"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        "idx_songs_props", "songs", ["properties"], unique=False, postgresql_using="gin"
    )
    op.create_index("idx_songs_url", "songs", ["url"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "user", name="role"),
            server_default="user",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "edit_jobs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("source_song_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "done",
                "failed",
                "duplicate",
                name="editjobstatus",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("result_song_id", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_song_id"], ["songs.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "error_logs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column("level", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_error_logs_timestamp", "error_logs", ["timestamp"], unique=False
    )
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "done",
                "failed",
                "duplicate",
                name="editjobstatus",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("song_id", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duplicate_of", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlists",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "song_downloads",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("song_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column(
            "downloaded_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["song_id"], ["songs.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_song_downloads_downloaded_at",
        "song_downloads",
        ["downloaded_at"],
        unique=False,
    )
    op.create_index(
        "idx_song_downloads_song_id", "song_downloads", ["song_id"], unique=False
    )
    op.create_table(
        "song_edit_drafts",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("song_id", sa.Text(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["song_id"], ["songs.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "song_id"),
    )
    op.create_table(
        "song_plays",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("song_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column(
            "played_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["song_id"], ["songs.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_song_plays_played_at", "song_plays", ["played_at"], unique=False
    )
    op.create_index("idx_song_plays_song_id", "song_plays", ["song_id"], unique=False)
    op.create_table(
        "song_share_tokens",
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("song_id", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_table(
        "user_offline_songs",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("song_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["song_id"], ["songs.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "song_id"),
    )
    op.create_table(
        "user_player_state",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("shuffle", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "repeat",
            sa.Enum("off", "one", "all", name="repeatmode"),
            server_default="off",
            nullable=False,
        ),
        sa.Column(
            "queue",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("queue_index", sa.Integer(), server_default="-1", nullable=False),
        sa.Column(
            "shuffle_order", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("play_context", sa.Text(), nullable=True),
        sa.Column("shuffle_seed", sa.Integer(), nullable=True),
        sa.Column("shuffle_position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "manual_next",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("current_song_uuid", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_songs",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("song_id", sa.Text(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column("last_position", sa.Float(), server_default="0", nullable=False),
        sa.Column("last_played_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["song_id"], ["songs.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "song_id"),
    )
    op.create_table(
        "playlist_songs",
        sa.Column("playlist_id", sa.Text(), nullable=False),
        sa.Column("song_uuid", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_uuid"], ["songs.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("playlist_id", "song_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist_songs")
    op.drop_table("user_songs")
    op.drop_table("user_player_state")
    op.drop_table("user_offline_songs")
    op.drop_table("song_share_tokens")
    op.drop_index("idx_song_plays_song_id", table_name="song_plays")
    op.drop_index("idx_song_plays_played_at", table_name="song_plays")
    op.drop_table("song_plays")
    op.drop_table("song_edit_drafts")
    op.drop_index("idx_song_downloads_song_id", table_name="song_downloads")
    op.drop_index("idx_song_downloads_downloaded_at", table_name="song_downloads")
    op.drop_table("song_downloads")
    op.drop_table("playlists")
    op.drop_table("import_jobs")
    op.drop_index("idx_error_logs_timestamp", table_name="error_logs")
    op.drop_table("error_logs")
    op.drop_table("edit_jobs")
    op.drop_table("users")
    op.drop_index("idx_songs_url", table_name="songs")
    op.drop_index("idx_songs_props", table_name="songs", postgresql_using="gin")
    op.drop_table("songs")
    # ### end Alembic commands ###
