name: docker
on:
  push:
    branches: [main]
    tags: '*'
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: cboin/songbirdapi
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${DOCKER_IMAGE}:latest
          cache-from: type=registry,ref=${DOCKER_IMAGE}:buildcache
          cache-to: type=registry,ref=${DOCKER_IMAGE}:buildcache,mode=max
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${DOCKER_IMAGE}:latest

